name: Release

on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  post_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload File Action
        uses: JantHsueh/upload-file-action@1.0
        with:
          url: https://tfs-bot.fm-96.at/post/405540621005357068
          forms: '{"jwt":"${{ secrets.POST_JWT }}", "clear":"true"}'
          fileForms: '{"612086761195044864":"rules.md", "831949662290182206":"rules-and-info.md"}'
